# Generated by Django 4.2.5 on 2023-10-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_head', models.CharField(max_length=50)),
                ('item_title', models.CharField(max_length=50)),
                ('item_descript', models.CharField(max_length=500)),
            ],
        ),
    ]
